### PR TITLE
Update BinaryAndroidApplication.java

### PR DESCRIPTION
**Pull request by firmianay**

### CODE REVIEW

**Comment by StevenArzt** [comment]
This PR changes the semantics of the parser. Currently, we let the user decide how to handle apps that don't specify the attribute. Keep in mind that the app behavior depends on the target SDK version in that case, so even if you wanted to handle it in FlowDroid, it would be much more complex.

**Comment by firmianay** [comment]
I understand, so I need to compare the API versions because the default values are different. Is it okay to do this like now?

**Comment by firmianay** [comment]
btw, for allowBackup, its default value is true, but the current code will return false

**Comment by StevenArzt** [comment]
You can fix "allowBackup", that's easy.

For the cleartext traffic, the logic is fairly complex. Keep in mind that Android also supports a network [security configuration](https://developer.android.com/training/articles/security-config), which is another file in the app in which you make similar settings. That's why we chose to give the user the "raw" data, which may be ``null``, and have the user deal with it.

Our commercial code scanner (which is built on top of Soot and FlowDroid) checks for the null value and then does the more complex reasoning including the other relevant files depending on the target SDK version.

**Review by StevenArzt — APPROVED** [review]

**Comment by firmianay** [comment]
OK, I've fixed the allowBackup error.

I used to think that this value was only for usesCleartextTraffic, but if you want to consider network security configuration at the same time, it is indeed more complicated. It will take some effort to parse this file.

**Pull request merged**
